// This file is different in the example, please use the auto generated file
/// <reference types="./example-env" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by react-native-css. If you need to move or disable this file, please see the documentation.
