/* eslint-disable */
import { existsSync, readFileSync, writeFileSync } from "fs";
import { dirname, relative, resolve } from "node:path";

import { CommentArray, parse, stringify } from "comment-json";

import { bold, cyan } from "./picocolors";

export function setupTypeScript(
  envPath = "react-native-css-env.d.ts",
  name = "react-native-css",
) {
  try {
    const ts = require("typescript");
    if (!ts) {
      return;
    }

    const configFileName = ts.findConfigFile(
      resolve("."),
      ts.sys.fileExists,
      "tsconfig.json",
    );

    if (!configFileName) return;

    const configDirectory = dirname(resolve(configFileName));
    const environmentFile = resolve(envPath);
    const relativeEnvironmentFile = relative(configDirectory, environmentFile);

    const userConfig = parse(
      readFileSync(configFileName, {
        encoding: "utf-8",
      }),
    );

    if (
      typeof userConfig !== "object" ||
      !userConfig ||
      Array.isArray(userConfig)
    ) {
      return;
    }

    const output: string[] = [];
    let updatedConfig = false;

    if (!existsSync(envPath)) {
      writeFileSync(
        envPath,
        `/// <reference types="react-native-css/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by ${name}. If you need to move or disable this file, please see the documentation.`,
      );
      output.push(`Created ${cyan(envPath)}`);
    }

    if (
      Array.isArray(userConfig.include) &&
      !(
        Array.isArray(userConfig.files) &&
        userConfig.files.includes(relativeEnvironmentFile)
      ) &&
      !userConfig.include.includes(relativeEnvironmentFile)
    ) {
      userConfig.include.push(relativeEnvironmentFile);
      updatedConfig = true;
      output.push(
        `Updated ${configFileName} to include the ${cyan(envPath)} file`,
      );
    }

    // Resolve inheritance on a copy so comments and the user's own settings survive.
    const effectiveConfig = ts.parseJsonConfigFileContent(
      JSON.parse(JSON.stringify(userConfig)),
      ts.sys,
      configDirectory,
      {},
      resolve(configFileName),
    );
    if (
      !effectiveConfig.fileNames.some(
        (file: string) => resolve(file) === environmentFile,
      )
    ) {
      // A files entry can include the declaration even when inherited include or
      // exclude settings omit it. Preserve the original implicit include as well.
      if (
        effectiveConfig.raw.include === undefined &&
        effectiveConfig.raw.files === undefined
      ) {
        userConfig.include = new CommentArray("**/*");
      }
      userConfig.files ??= new CommentArray(
        ...(effectiveConfig.raw.files || []),
      );
      if (
        Array.isArray(userConfig.files) &&
        !userConfig.files.includes(relativeEnvironmentFile)
      ) {
        userConfig.files.push(relativeEnvironmentFile);
        updatedConfig = true;
        output.push(
          `Updated ${configFileName} to include the ${cyan(envPath)} file`,
        );
      }
    }

    if (updatedConfig) {
      writeFileSync(configFileName, stringify(userConfig, null, 2));
    }

    if (output.length) {
      console.log(
        `${cyan(bold("Nativewind"))} made the following changes to your project to support TypeScript:\n  - ${output.join("\n  - ")}`,
      );
    }
  } catch {}
}
